// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#pragma once

#include "djinni_support.hpp"
#include "login_status_callback.hpp"

namespace djinni_generated {

class NativeLoginStatusCallback final : ::djinni::JniInterface<::UserLogin::LoginStatusCallback, NativeLoginStatusCallback> {
public:
    using CppType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using CppOptType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using JniType = jobject;

    using Boxed = NativeLoginStatusCallback;

    ~NativeLoginStatusCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLoginStatusCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLoginStatusCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLoginStatusCallback();
    friend ::djinni::JniClass<NativeLoginStatusCallback>;
    friend ::djinni::JniInterface<::UserLogin::LoginStatusCallback, NativeLoginStatusCallback>;

};

}  // namespace djinni_generated
