// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#include "NativeLoginStatusCallback.hpp"  // my header

namespace djinni_generated {

NativeLoginStatusCallback::NativeLoginStatusCallback() : ::djinni::JniInterface<::UserLogin::LoginStatusCallback, NativeLoginStatusCallback>("com/single/user/login/LoginStatusCallback$CppProxy") {}

NativeLoginStatusCallback::~NativeLoginStatusCallback() = default;


CJNIEXPORT void JNICALL Java_com_single_user_login_LoginStatusCallback_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::UserLogin::LoginStatusCallback>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_single_user_login_LoginStatusCallback_00024CppProxy_native_1onLoginSucc(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::UserLogin::LoginStatusCallback>(nativeRef);
        ref->onLoginSucc();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_single_user_login_LoginStatusCallback_00024CppProxy_native_1onLoginOut(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::UserLogin::LoginStatusCallback>(nativeRef);
        ref->onLoginOut();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_single_user_login_LoginStatusCallback_00024CppProxy_native_1onLoginFailed(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::UserLogin::LoginStatusCallback>(nativeRef);
        ref->onLoginFailed();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
