// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#pragma once

#include <cstdint>
#include <string>

namespace UserLogin {

class LoginStatusCallback {
public:
    virtual ~LoginStatusCallback() {}

    virtual void onLoginSucc() = 0;

    virtual void onLoginOut(int32_t retCode, const std::string & msg) = 0;

    virtual void onLoginFailed(int32_t retCode, const std::string & msg) = 0;

    virtual void onSignUpSucc() = 0;

    virtual void onSignUpFailed(int32_t retCode, const std::string & msg) = 0;
};

}  // namespace UserLogin
