// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

package com.single.user.login;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ interface LoginStatusCallback {
    public void onLoginSucc();

    public void onLoginOut(int retCode, @Nonnull String msg);

    public void onLoginFailed(int retCode, @Nonnull String msg);

    public void onSignUpSucc();

    public void onSignUpFailed(int retCode, @Nonnull String msg);
}
