// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#pragma once

#include "djinni_support.hpp"
#include "login_status_callback.hpp"

namespace djinni_generated {

class NativeLoginStatusCallback final : ::djinni::JniInterface<::UserLogin::LoginStatusCallback, NativeLoginStatusCallback> {
public:
    using CppType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using CppOptType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using JniType = jobject;

    using Boxed = NativeLoginStatusCallback;

    ~NativeLoginStatusCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLoginStatusCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLoginStatusCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLoginStatusCallback();
    friend ::djinni::JniClass<NativeLoginStatusCallback>;
    friend ::djinni::JniInterface<::UserLogin::LoginStatusCallback, NativeLoginStatusCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::UserLogin::LoginStatusCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onLoginSucc() override;
        void onLoginOut(int32_t retCode, const std::string & msg) override;
        void onLoginFailed(int32_t retCode, const std::string & msg) override;
        void onSignUpSucc() override;
        void onSignUpFailed(int32_t retCode, const std::string & msg) override;

    private:
        friend ::djinni::JniInterface<::UserLogin::LoginStatusCallback, ::djinni_generated::NativeLoginStatusCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/single/user/login/LoginStatusCallback") };
    const jmethodID method_onLoginSucc { ::djinni::jniGetMethodID(clazz.get(), "onLoginSucc", "()V") };
    const jmethodID method_onLoginOut { ::djinni::jniGetMethodID(clazz.get(), "onLoginOut", "(ILjava/lang/String;)V") };
    const jmethodID method_onLoginFailed { ::djinni::jniGetMethodID(clazz.get(), "onLoginFailed", "(ILjava/lang/String;)V") };
    const jmethodID method_onSignUpSucc { ::djinni::jniGetMethodID(clazz.get(), "onSignUpSucc", "()V") };
    const jmethodID method_onSignUpFailed { ::djinni::jniGetMethodID(clazz.get(), "onSignUpFailed", "(ILjava/lang/String;)V") };
};

}  // namespace djinni_generated
