// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#include "login_status_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TXSLoginStatusCallback;

namespace djinni_generated {

class LoginStatusCallback
{
public:
    using CppType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using CppOptType = std::shared_ptr<::UserLogin::LoginStatusCallback>;
    using ObjcType = id<TXSLoginStatusCallback>;

    using Boxed = LoginStatusCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

