// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#import <Foundation/Foundation.h>
@class TXSUserLogin;
@protocol TXSLoginStatusCallback;


@interface TXSUserLogin : NSObject

- (int32_t)signUp:(nonnull NSString *)userName
              pwd:(nonnull NSString *)pwd
         callback:(nullable id<TXSLoginStatusCallback>)callback;

- (int32_t)login:(nonnull NSString *)userName
             pwd:(nonnull NSString *)pwd
        callback:(nullable id<TXSLoginStatusCallback>)callback;

- (int32_t)logout:(nonnull NSString *)userName
              pwd:(nonnull NSString *)pwd
         callback:(nullable id<TXSLoginStatusCallback>)callback;

+ (nullable TXSUserLogin *)createUserInterface;

@end
