// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#import <Foundation/Foundation.h>


@interface UserLogin_LoginStatusCallback : NSObject

- (void)onLoginSucc;

- (void)onLoginOut;

- (void)onLoginFailed;

@end
