// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#import "TXSLoginStatusCallback+Private.h"
#import "TXSLoginStatusCallback.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class LoginStatusCallback::ObjcProxy final
: public ::UserLogin::LoginStatusCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::LoginStatusCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onLoginSucc() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginSucc];
        }
    }
    void onLoginOut(int32_t c_retCode, const std::string & c_msg) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginOut:(::djinni::I32::fromCpp(c_retCode))
                                                             msg:(::djinni::String::fromCpp(c_msg))];
        }
    }
    void onLoginFailed(int32_t c_retCode, const std::string & c_msg) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginFailed:(::djinni::I32::fromCpp(c_retCode))
                                                                msg:(::djinni::String::fromCpp(c_msg))];
        }
    }
    void onSignUpSucc() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onSignUpSucc];
        }
    }
    void onSignUpFailed(int32_t c_retCode, const std::string & c_msg) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onSignUpFailed:(::djinni::I32::fromCpp(c_retCode))
                                                                 msg:(::djinni::String::fromCpp(c_msg))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto LoginStatusCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto LoginStatusCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
