// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#import <Foundation/Foundation.h>


@protocol TXSLoginStatusCallback

- (void)onLoginSucc;

- (void)onLoginOut:(int32_t)retCode
               msg:(nonnull NSString *)msg;

- (void)onLoginFailed:(int32_t)retCode
                  msg:(nonnull NSString *)msg;

- (void)onSignUpSucc;

- (void)onSignUpFailed:(int32_t)retCode
                   msg:(nonnull NSString *)msg;

@end
