// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// UserLogin_Bridging_Header.h
// UserLogin_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for UserLoginBridgingHeader.
FOUNDATION_EXPORT double UserLoginBridgingHeaderVersionNumber;

//! Project version string for UserLoginBridgingHeader.
FOUNDATION_EXPORT const unsigned char UserLoginBridgingHeaderVersionString[];

#import "TXSUserLogin.h"
#import "TXSLoginStatusCallback.h"
