// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#import "UserLogin_LoginStatusCallback+Private.h"
#import "UserLogin_LoginStatusCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface UserLogin_LoginStatusCallback ()

- (id)initWithCpp:(const std::shared_ptr<::UserLogin::LoginStatusCallback>&)cppRef;

@end

@implementation UserLogin_LoginStatusCallback {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::UserLogin::LoginStatusCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::UserLogin::LoginStatusCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onLoginSucc {
    try {
        _cppRefHandle.get()->onLoginSucc();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onLoginOut {
    try {
        _cppRefHandle.get()->onLoginOut();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onLoginFailed {
    try {
        _cppRefHandle.get()->onLoginFailed();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto LoginStatusCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto LoginStatusCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<UserLogin_LoginStatusCallback>(cpp);
}

}  // namespace djinni_generated

@end
