// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from UserLogin.djinni

#pragma once

namespace UserLogin {

class LoginStatusCallback {
public:
    virtual ~LoginStatusCallback() {}

    virtual void onLoginSucc() = 0;

    virtual void onLoginOut() = 0;

    virtual void onLoginFailed() = 0;
};

}  // namespace UserLogin
